version: '3.8'

services:
        
  db:
    build: ./infra/Mysql
    env_file:
      - ./infra/mysql/db.env
    restart: always
    ports:
      - "3310:3306"
    networks:
      - LaravelNetwork
  
  laravel:
      depends_on:
        - db
        - redis
      build: 
        context: ./
        dockerfile: ./Infra/Laravel/Dockerfile
      restart: always
      volumes:
          - ./src:/var/www/localhost/htdocs
      networks:
        - LaravelNetwork

  redis:
      image: redis:latest
      networks:
          - LaravelNetwork
          
  nginx:
      image: nginx:latest
      depends_on:
        - laravel
      restart: unless-stopped
      ports:
        - "8080:80"
      volumes:
        - ./Infra/Nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./Infra/Nginx/default.conf:/etc/nginx/conf.d/default.conf
      networks:
        - LaravelNetwork
          
        
networks: 
  LaravelNetwork: {}
  